<#
.SYNOPSIS
    Windows Forms GUI for WinCopy. Lets the user pick a source folder,
    destination folder, and a schedule (either daily at a chosen time or
    at a repeating interval up to every 60 minutes / 24 hours), then
    registers a Windows Task Scheduler job that invokes WinCopy-Run.ps1
    on that schedule. Also lets the user view and delete the scheduled
    task from the GUI itself.

.NOTES
    Run with:  powershell -ExecutionPolicy Bypass -File WinCopy-GUI.ps1
#>

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfigPath = Join-Path $ScriptDir 'winCopy-config.json'
$RunScript  = Join-Path $ScriptDir 'WinCopy-Run.ps1'
$VbsLauncher = Join-Path $ScriptDir 'WinCopy-Hidden.vbs'
$TaskName   = 'WinCopyDailyJob'

# Make sure a VBS launcher exists so the scheduled task can run PowerShell
# completely hidden (no console window flashes up on every interval).
function Ensure-VbsLauncher {
    $vbs = @'
' WinCopy-Hidden.vbs - launches WinCopy-Run.ps1 without showing any window.
' Generated by WinCopy-GUI.ps1; safe to delete (will be re-created).
Option Explicit
Dim shell, scriptDir, ps1, cmd
Set shell  = CreateObject("WScript.Shell")
scriptDir  = CreateObject("Scripting.FileSystemObject").GetParentFolderName(WScript.ScriptFullName)
ps1        = scriptDir & "\WinCopy-Run.ps1"
cmd        = "powershell.exe -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File """ & ps1 & """"
' Run hidden (0), do not wait.
shell.Run cmd, 0, False
'@
    Set-Content -Path $VbsLauncher -Value $vbs -Encoding ASCII
}

# Allowed interval choices for the two dropdowns
$IntervalValues = @(1, 2, 5, 10, 15, 20, 30, 45, 60)
$IntervalUnits  = @('Minutes', 'Hours')

# ----- Load existing config if present -----
$initialSource        = ''
$initialDest          = ''
$initialTime          = [DateTime]::Today.AddHours(22)  # default 22:00
$initialMode          = 'Daily'                          # 'Daily' or 'Interval'
$initialIntervalValue = 2
$initialIntervalUnit  = 'Minutes'
if (Test-Path $ConfigPath) {
    try {
        $cfg = Get-Content $ConfigPath -Raw | ConvertFrom-Json
        if ($cfg.source)      { $initialSource = $cfg.source }
        if ($cfg.destination) { $initialDest   = $cfg.destination }
        if ($cfg.runTime) {
            $parsed = [DateTime]::MinValue
            if ([DateTime]::TryParse("$(Get-Date -Format yyyy-MM-dd) $($cfg.runTime)", [ref]$parsed)) {
                $initialTime = $parsed
            }
        }
        if ($cfg.scheduleMode) {
            # Migrate legacy 'Every2Minutes' mode to the new 'Interval' mode
            if ($cfg.scheduleMode -eq 'Every2Minutes') {
                $initialMode          = 'Interval'
                $initialIntervalValue = 2
                $initialIntervalUnit  = 'Minutes'
            } else {
                $initialMode = $cfg.scheduleMode
            }
        }
        if ($cfg.intervalValue) {
            try { $initialIntervalValue = [int]$cfg.intervalValue } catch { }
        }
        if ($cfg.intervalUnit -and ($IntervalUnits -contains $cfg.intervalUnit)) {
            $initialIntervalUnit = $cfg.intervalUnit
        }
    } catch { }
}
if (-not ($IntervalValues -contains $initialIntervalValue)) {
    $initialIntervalValue = 2
}

# ----- Form -----
$form               = New-Object System.Windows.Forms.Form
$form.Text          = 'WinCopy - Schedule Folder Copy'
$form.Size          = New-Object System.Drawing.Size(620, 420)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.MaximizeBox   = $false

# Source row
$lblSource = New-Object System.Windows.Forms.Label
$lblSource.Text = 'Source folder:'
$lblSource.Location = New-Object System.Drawing.Point(15, 20)
$lblSource.Size = New-Object System.Drawing.Size(100, 22)
$form.Controls.Add($lblSource)

$txtSource = New-Object System.Windows.Forms.TextBox
$txtSource.Location = New-Object System.Drawing.Point(120, 18)
$txtSource.Size = New-Object System.Drawing.Size(330, 22)
$txtSource.Text = $initialSource
$form.Controls.Add($txtSource)

$btnSource = New-Object System.Windows.Forms.Button
$btnSource.Text = 'Browse...'
$btnSource.Location = New-Object System.Drawing.Point(460, 17)
$btnSource.Size = New-Object System.Drawing.Size(75, 24)
$btnSource.Add_Click({
    $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
    if ($txtSource.Text) { $dlg.SelectedPath = $txtSource.Text }
    if ($dlg.ShowDialog() -eq 'OK') { $txtSource.Text = $dlg.SelectedPath }
})
$form.Controls.Add($btnSource)

# Destination row
$lblDest = New-Object System.Windows.Forms.Label
$lblDest.Text = 'Destination folder:'
$lblDest.Location = New-Object System.Drawing.Point(15, 60)
$lblDest.Size = New-Object System.Drawing.Size(110, 22)
$form.Controls.Add($lblDest)

$txtDest = New-Object System.Windows.Forms.TextBox
$txtDest.Location = New-Object System.Drawing.Point(120, 58)
$txtDest.Size = New-Object System.Drawing.Size(330, 22)
$txtDest.Text = $initialDest
$form.Controls.Add($txtDest)

$btnDest = New-Object System.Windows.Forms.Button
$btnDest.Text = 'Browse...'
$btnDest.Location = New-Object System.Drawing.Point(460, 57)
$btnDest.Size = New-Object System.Drawing.Size(75, 24)
$btnDest.Add_Click({
    $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
    if ($txtDest.Text) { $dlg.SelectedPath = $txtDest.Text }
    if ($dlg.ShowDialog() -eq 'OK') { $txtDest.Text = $dlg.SelectedPath }
})
$form.Controls.Add($btnDest)

# Schedule mode row
$lblMode = New-Object System.Windows.Forms.Label
$lblMode.Text = 'Schedule:'
$lblMode.Location = New-Object System.Drawing.Point(15, 100)
$lblMode.Size = New-Object System.Drawing.Size(100, 22)
$form.Controls.Add($lblMode)

$rbDaily = New-Object System.Windows.Forms.RadioButton
$rbDaily.Text = 'Daily at'
$rbDaily.Location = New-Object System.Drawing.Point(120, 98)
$rbDaily.Size = New-Object System.Drawing.Size(80, 24)
$rbDaily.Checked = ($initialMode -ne 'Interval')
$form.Controls.Add($rbDaily)

$dtpTime = New-Object System.Windows.Forms.DateTimePicker
$dtpTime.Format = [System.Windows.Forms.DateTimePickerFormat]::Custom
$dtpTime.CustomFormat = 'hh:mm tt'
$dtpTime.ShowUpDown = $true
$dtpTime.Location = New-Object System.Drawing.Point(205, 98)
$dtpTime.Size = New-Object System.Drawing.Size(95, 22)
$dtpTime.Value = $initialTime
$form.Controls.Add($dtpTime)

# Interval row: "Every <N> <unit>"
$rbInterval = New-Object System.Windows.Forms.RadioButton
$rbInterval.Text = 'Every'
$rbInterval.Location = New-Object System.Drawing.Point(120, 132)
$rbInterval.Size = New-Object System.Drawing.Size(65, 24)
$rbInterval.Checked = ($initialMode -eq 'Interval')
$form.Controls.Add($rbInterval)

$cmbIntervalValue = New-Object System.Windows.Forms.ComboBox
$cmbIntervalValue.DropDownStyle = [System.Windows.Forms.ComboBoxStyle]::DropDownList
$cmbIntervalValue.Location = New-Object System.Drawing.Point(190, 132)
$cmbIntervalValue.Size = New-Object System.Drawing.Size(60, 22)
foreach ($v in $IntervalValues) { [void]$cmbIntervalValue.Items.Add($v) }
$cmbIntervalValue.SelectedItem = $initialIntervalValue
$form.Controls.Add($cmbIntervalValue)

$cmbIntervalUnit = New-Object System.Windows.Forms.ComboBox
$cmbIntervalUnit.DropDownStyle = [System.Windows.Forms.ComboBoxStyle]::DropDownList
$cmbIntervalUnit.Location = New-Object System.Drawing.Point(255, 132)
$cmbIntervalUnit.Size = New-Object System.Drawing.Size(90, 22)
foreach ($u in $IntervalUnits) { [void]$cmbIntervalUnit.Items.Add($u) }
$cmbIntervalUnit.SelectedItem = $initialIntervalUnit
$form.Controls.Add($cmbIntervalUnit)

# Enable/disable inputs based on selected mode
$updateModeEnabled = {
    $dtpTime.Enabled          = $rbDaily.Checked
    $cmbIntervalValue.Enabled = $rbInterval.Checked
    $cmbIntervalUnit.Enabled  = $rbInterval.Checked
}
$rbDaily.Add_CheckedChanged($updateModeEnabled)
$rbInterval.Add_CheckedChanged($updateModeEnabled)
& $updateModeEnabled

# Status label
$lblStatus = New-Object System.Windows.Forms.Label
$lblStatus.Location = New-Object System.Drawing.Point(15, 280)
$lblStatus.Size = New-Object System.Drawing.Size(580, 60)
$lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
$lblStatus.Text = ''
$form.Controls.Add($lblStatus)

# Helpers
function Validate-Inputs {
    if (-not $txtSource.Text -or -not (Test-Path $txtSource.Text)) {
        [System.Windows.Forms.MessageBox]::Show('Source folder does not exist.', 'WinCopy', 'OK', 'Error') | Out-Null
        return $false
    }
    if (-not $txtDest.Text) {
        [System.Windows.Forms.MessageBox]::Show('Destination folder is required.', 'WinCopy', 'OK', 'Error') | Out-Null
        return $false
    }
    return $true
}

function Save-Config {
    $runTime    = $dtpTime.Value.ToString('HH:mm')
    $runDisplay = $dtpTime.Value.ToString('hh:mm tt')
    $mode       = if ($rbInterval.Checked) { 'Interval' } else { 'Daily' }
    $intervalValue = [int]$cmbIntervalValue.SelectedItem
    $intervalUnit  = [string]$cmbIntervalUnit.SelectedItem
    $cfg = [PSCustomObject]@{
        source        = $txtSource.Text
        destination   = $txtDest.Text
        runTime       = $runTime
        scheduleMode  = $mode
        intervalValue = $intervalValue
        intervalUnit  = $intervalUnit
    }
    $cfg | ConvertTo-Json | Set-Content -Path $ConfigPath -Encoding UTF8
    return [PSCustomObject]@{
        RunTime       = $runTime
        RunDisplay    = $runDisplay
        Mode          = $mode
        IntervalValue = $intervalValue
        IntervalUnit  = $intervalUnit
    }
}

function Register-WinCopyTask {
    param(
        [string]$RunTime,
        [string]$Mode,
        [int]$IntervalValue,
        [string]$IntervalUnit
    )

    if ($Mode -eq 'Interval') {
        # Trigger: starts ~1 minute from now, repeats at the chosen interval
        # "indefinitely". Task Scheduler requires a finite RepetitionDuration,
        # so use a long span.
        $startAt = (Get-Date).AddMinutes(1)
        if ($IntervalUnit -eq 'Hours') {
            $interval = New-TimeSpan -Hours $IntervalValue
        } else {
            $interval = New-TimeSpan -Minutes $IntervalValue
        }
        $trigger = New-ScheduledTaskTrigger -Once -At $startAt `
                        -RepetitionInterval $interval `
                        -RepetitionDuration (New-TimeSpan -Days 3650)
        $description = "WinCopy: folder copy job, every $IntervalValue $($IntervalUnit.ToLower())"
    } else {
        # Trigger: daily at the given HH:mm
        $trigger     = New-ScheduledTaskTrigger -Daily -At $RunTime
        $description = 'WinCopy: daily folder copy job'
    }

    # Action: run the VBS launcher via wscript so no console window appears
    Ensure-VbsLauncher
    $wscriptExe = Join-Path $env:WINDIR 'System32\wscript.exe'
    if (-not (Test-Path $wscriptExe)) { $wscriptExe = 'wscript.exe' }
    $action = New-ScheduledTaskAction `
        -Execute $wscriptExe `
        -Argument "`"$VbsLauncher`""

    $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden

    # Remove existing task first, ignore errors
    try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue } catch { }

    Register-ScheduledTask `
        -TaskName $TaskName `
        -Trigger $trigger `
        -Action $action `
        -Settings $settings `
        -Description $description `
        -RunLevel Limited | Out-Null
}

function Get-WinCopyTaskInfo {
    try {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        $info = Get-ScheduledTaskInfo -TaskName $TaskName -ErrorAction Stop

        # Summarize triggers (Daily HH:mm, or Once every N <unit>).
        $triggerSummaries = @()
        foreach ($t in $task.Triggers) {
            $cls = $t.CimClass.CimClassName
            switch ($cls) {
                'MSFT_TaskDailyTrigger' {
                    $startBoundary = $null
                    try { $startBoundary = [DateTime]::Parse($t.StartBoundary) } catch { }
                    $when = if ($startBoundary) { $startBoundary.ToString('hh:mm tt') } else { $t.StartBoundary }
                    $triggerSummaries += "Daily at $when"
                }
                'MSFT_TaskTimeTrigger' {
                    $startBoundary = $null
                    try { $startBoundary = [DateTime]::Parse($t.StartBoundary) } catch { }
                    $startTxt = if ($startBoundary) { $startBoundary.ToString('yyyy-MM-dd hh:mm tt') } else { $t.StartBoundary }
                    if ($t.Repetition -and $t.Repetition.Interval) {
                        # Repetition.Interval is an ISO 8601 duration like PT2M / PT1H.
                        $iso = $t.Repetition.Interval
                        try {
                            $ts = [System.Xml.XmlConvert]::ToTimeSpan($iso)
                            if ($ts.TotalMinutes -lt 60) {
                                $every = "$([int]$ts.TotalMinutes) minute(s)"
                            } else {
                                $every = "$([int]$ts.TotalHours) hour(s)"
                            }
                            $triggerSummaries += "Every $every (started $startTxt)"
                        } catch {
                            $triggerSummaries += "Repeats every $iso (started $startTxt)"
                        }
                    } else {
                        $triggerSummaries += "Once at $startTxt"
                    }
                }
                default { $triggerSummaries += $cls }
            }
        }
        if (-not $triggerSummaries) { $triggerSummaries = @('(no triggers)') }

        return [PSCustomObject]@{
            Exists             = $true
            State              = $task.State
            Description        = $task.Description
            LastRunTime        = $info.LastRunTime
            LastResult         = $info.LastTaskResult
            NextRunTime        = $info.NextRunTime
            NumberOfMissedRuns = $info.NumberOfMissedRuns
            Triggers           = $triggerSummaries
        }
    } catch {
        return [PSCustomObject]@{ Exists = $false }
    }
}

function Format-TaskTime {
    param($value)
    if (-not $value) { return 'Never' }
    try {
        $dt = [DateTime]$value
        # Task Scheduler returns a sentinel like 1899-12-30 when the value is unset.
        if ($dt.Year -lt 1900) { return 'Never' }
        return $dt.ToString('yyyy-MM-dd hh:mm:ss tt')
    } catch {
        return [string]$value
    }
}

# Save & Schedule button
$btnSave = New-Object System.Windows.Forms.Button
$btnSave.Text = 'Save && Schedule'
$btnSave.Location = New-Object System.Drawing.Point(15, 230)
$btnSave.Size = New-Object System.Drawing.Size(140, 32)
$btnSave.Add_Click({
    if (-not (Validate-Inputs)) { return }
    try {
        $saved = Save-Config
        Register-WinCopyTask -RunTime $saved.RunTime -Mode $saved.Mode `
            -IntervalValue $saved.IntervalValue -IntervalUnit $saved.IntervalUnit
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkGreen
        if ($saved.Mode -eq 'Interval') {
            $lblStatus.Text = "Scheduled to run every $($saved.IntervalValue) $($saved.IntervalUnit.ToLower()). Task name: $TaskName"
        } else {
            $lblStatus.Text = "Scheduled daily at $($saved.RunDisplay). Task name: $TaskName"
        }
    } catch {
        $lblStatus.ForeColor = [System.Drawing.Color]::Red
        $lblStatus.Text = "Failed to schedule: $($_.Exception.Message)"
    }
})
$form.Controls.Add($btnSave)

# Run Now button
$btnRun = New-Object System.Windows.Forms.Button
$btnRun.Text = 'Run Now'
$btnRun.Location = New-Object System.Drawing.Point(165, 230)
$btnRun.Size = New-Object System.Drawing.Size(90, 32)
$btnRun.Add_Click({
    if (-not (Validate-Inputs)) { return }
    try {
        [void](Save-Config)
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
        $lblStatus.Text = 'Running copy now...'
        $form.Refresh()
        $psExe = (Get-Command powershell.exe).Source
        $p = Start-Process -FilePath $psExe `
            -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $RunScript) `
            -WindowStyle Hidden -PassThru -Wait
        if ($p.ExitCode -eq 0) {
            $lblStatus.ForeColor = [System.Drawing.Color]::DarkGreen
            $lblStatus.Text = 'Run Now completed successfully. See winCopy.log for details.'
        } else {
            $lblStatus.ForeColor = [System.Drawing.Color]::Red
            $lblStatus.Text = "Run Now finished with errors (exit $($p.ExitCode)). See winCopy.log."
        }
    } catch {
        $lblStatus.ForeColor = [System.Drawing.Color]::Red
        $lblStatus.Text = "Run failed: $($_.Exception.Message)"
    }
})
$form.Controls.Add($btnRun)

# View Task button (shows task status in a popup)
$btnView = New-Object System.Windows.Forms.Button
$btnView.Text = 'View Task'
$btnView.Location = New-Object System.Drawing.Point(265, 230)
$btnView.Size = New-Object System.Drawing.Size(90, 32)
$btnView.Add_Click({
    $info = Get-WinCopyTaskInfo
    if (-not $info.Exists) {
        [System.Windows.Forms.MessageBox]::Show(
            "No scheduled task named '$TaskName' exists. Use Save & Schedule to create one.",
            'WinCopy - View Task', 'OK', 'Information') | Out-Null
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
        $lblStatus.Text = "No scheduled task '$TaskName' exists yet."
        return
    }
    $lastResultHex = '0x{0:X}' -f [int]$info.LastResult
    $triggerText   = ($info.Triggers -join "`r`n              ")
    $lastRunText   = Format-TaskTime $info.LastRunTime
    $nextRunText   = Format-TaskTime $info.NextRunTime
    $msg = @"
Task name:    $TaskName
State:        $($info.State)
Description:  $($info.Description)
Schedule:     $triggerText

Last run:     $lastRunText
Last result:  $($info.LastResult) ($lastResultHex)
Next run:     $nextRunText
Missed runs:  $($info.NumberOfMissedRuns)
"@
    [System.Windows.Forms.MessageBox]::Show($msg, 'WinCopy - View Task', 'OK', 'Information') | Out-Null
    $lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
    $lblStatus.Text = "Task '$TaskName' state: $($info.State); next run: $nextRunText."
})
$form.Controls.Add($btnView)

# Delete Task button (with confirmation)
$btnDelete = New-Object System.Windows.Forms.Button
$btnDelete.Text = 'Delete Task'
$btnDelete.Location = New-Object System.Drawing.Point(365, 230)
$btnDelete.Size = New-Object System.Drawing.Size(95, 32)
$btnDelete.Add_Click({
    $info = Get-WinCopyTaskInfo
    if (-not $info.Exists) {
        [System.Windows.Forms.MessageBox]::Show(
            "No scheduled task named '$TaskName' exists.",
            'WinCopy - Delete Task', 'OK', 'Information') | Out-Null
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
        $lblStatus.Text = "No scheduled task '$TaskName' to delete."
        return
    }
    $answer = [System.Windows.Forms.MessageBox]::Show(
        "Delete scheduled task '$TaskName'?`r`n`r`nThis only removes the schedule; your files are untouched.",
        'WinCopy - Confirm Delete', 'YesNo', 'Warning')
    if ($answer -ne [System.Windows.Forms.DialogResult]::Yes) { return }
    try {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction Stop
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkGreen
        $lblStatus.Text = "Scheduled task '$TaskName' deleted."
    } catch {
        $lblStatus.ForeColor = [System.Drawing.Color]::Red
        $lblStatus.Text = "Failed to delete task: $($_.Exception.Message)"
    }
})
$form.Controls.Add($btnDelete)

# Open Log button
$btnLog = New-Object System.Windows.Forms.Button
$btnLog.Text = 'Open Log'
$btnLog.Location = New-Object System.Drawing.Point(470, 230)
$btnLog.Size = New-Object System.Drawing.Size(90, 32)
$btnLog.Add_Click({
    $logPath = Join-Path $ScriptDir 'winCopy.log'
    if (Test-Path $logPath) {
        Start-Process notepad.exe $logPath
    } else {
        $lblStatus.ForeColor = [System.Drawing.Color]::DarkBlue
        $lblStatus.Text = 'No log file yet (winCopy.log will be created on first run).'
    }
})
$form.Controls.Add($btnLog)

# Close button
$btnClose = New-Object System.Windows.Forms.Button
$btnClose.Text = 'Close'
$btnClose.Location = New-Object System.Drawing.Point(470, 350)
$btnClose.Size = New-Object System.Drawing.Size(90, 28)
$btnClose.Add_Click({ $form.Close() })
$form.Controls.Add($btnClose)

[void]$form.ShowDialog()
